"""empty message

Revision ID: 94a416772928
Revises: 643de7c23b44
Create Date: 2022-05-19 20:05:08.720324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94a416772928'
down_revision = '643de7c23b44'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=120),
               existing_nullable=False
               )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=sa.String(length=120),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using = 'start_time::timestamp without time zone',
               )
    # ### end Alembic commands ###
